wandb_version: 1

path:
  desc: null
  value: wandb_test
_wandb:
  desc: null
  value:
    python_version: 3.8.18
    cli_version: 0.16.1
    is_jupyter_run: false
    is_kaggle_kernel: false
    start_time: 1704663975.637426
    t:
      1:
      - 55
      2:
      - 55
      3:
      - 16
      - 23
      4: 3.8.18
      5: 0.16.1
      8:
      - 5
      13: linux-x86_64
